apiVersion: v1
kind: Service
metadata:
  labels:
    letschess.service: aiservice
  name: aiservice
  namespace: letschess
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6041
    targetPort: 80
  - name: "https"
    port: 6042
    targetPort: 443
  selector:
    letschess.service: aiservice
status:
  loadBalancer: {}