apiVersion: v1
kind: PersistentVolume
metadata:
  name: letschess-logging-volume
  namespace: letschess
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"