apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  namespace: letschess
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/rabbitmq/mnesia"