apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: letschess-mq
  namespace: letschess
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 100m
    limits:
      cpu: 2
      memory: 2Gi
  persistence:
    storage: "2Gi"
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []