apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-ready
  namespace: letschess
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 100m
    limits:
      cpu: 2
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
 #   storageClassName: ssd
    storage: "100m"
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []