apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: letschess-mq
  namespace: letschess
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: letschess-mq
---
