apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  namespace: letschess
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: production-ready-rabbitmq
  namespace: letschess
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: production-ready