apiVersion: v1
kind: Service
metadata:
  labels:
    letschess.service: chatservice
  name: chatservice
  namespace: letschess
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6051
    targetPort: 80
  - name: "https"
    port: 6052
    targetPort: 443
  selector:
    letschess.service: chatservice
status:
  loadBalancer: {}