apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    letschess.service: chatservice
  name: chatservice
  namespace: letschess
spec:
  replicas: 1
  selector:
    matchLabels:
      letschess.service: chatservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        letschess.service: chatservice
    spec:
      containers:
      - image: sacation/letschess-chatservice:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        name: letschess-chatservice
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
      hostname: chatservice
      restartPolicy: Always
      serviceAccountName: ""
status: {}
