apiVersion: v1
kind: Service
metadata:
  labels:
    letschess.service: letschessbackend
  name: letschessbackend
  namespace: letschess
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6011
    targetPort: 80
  - name: "https"
    port: 6012
    targetPort: 443
  selector:
    letschess.service: letschessbackend
status:
  loadBalancer: {}