apiVersion: v1
kind: Service
metadata:
  labels:
    letschess.service: userservice
  name: userservice
  namespace: letschess
spec:
  type: LoadBalancer
  ports:
  - name: "userservice-api-http-port"
    port: 6001
    targetPort: 80
  - name: "userservice-api-https-port"
    port: 6002
    targetPort: 443
  selector:
    letschess.service: userservice
status:
  loadBalancer: {}