# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: letschess-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: / # removes the prefix inside the service
#     cert-manager.io/issuer: letschess-selfsigned
#     # --default-ssl-certificate=default/letschess-cert
# spec:
#   defaultBackend:
#     service:
#       name: letschessfrontend
#       port: 
#         number: 3000
#   rules:
#   # - host: localhost
#     http:
#       paths:
#       - path: /users
#         pathType: Prefix
#         backend:
#           service:
#             name: userservice
#             port: 
#               number: 80
#       - path: /front
#         pathType: Prefix
#         backend:
#           service:
#             name: letschessfrontend
#             port: 
#               number: 3000
#       - path: /user
#         pathType: Prefix
#         backend:
#           service:
#             name: userservice
#             port: 
#               number: 443
#   tls:
#   - hosts:
#     - localhost
#     secretName: letschess-cert-tls