apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userservice-db-data
  namespace: letschess
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
