apiVersion: v1
kind: Service
metadata:
  labels:
    letschess.service: letschessfrontend
  name: letschessfrontend
  namespace: letschess
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000
  selector:
    letschess.service: letschessfrontend
status:
  loadBalancer: {}