apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letschess-ingress
  namespace: letschess
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: letschess.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: letschessfrontend
            port: 
              number: 3000
  - host: api.letschess.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: letschessbackend
            port: 
              number: 6011

#temp for debug only:
  - host: userservice.letschess.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: userservice
            port: 
              number: 6001
  - host: matchmakingservice.letschess.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: matchmakingservice
            port: 
              number: 6021
  - host: gameservice.letschess.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: gameservice
            port: 
              number: 6031
  - host: aiservice.letschess.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: aiservice
            port: 
              number: 6041
  - host: chatservice.letschess.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: chatservice
            port: 
              number: 6051
  - host: log.letschess.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana
            port: 
              number: 5601
          