apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letschess-ingress
  namespace: letschess
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        host: api.letschess.nl
        pathType: Prefix
        backend:
          service:
            name: letschessbackend
            port: 
              number: 6011
      - path: /
        host: letschess.nl
        pathType: Prefix
        backend:
          service:
            name: letschessfrontend
            port: 
              number: 3000