apiVersion: v1
kind: Service
metadata:
  labels:
    letschess.service: gameservice
  name: gameservice
  namespace: letschess
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6031
    targetPort: 80
  - name: "https"
    port: 6032
    targetPort: 443
  selector:
    letschess.service: gameservice
status:
  loadBalancer: {}